CREATE TABLE "ADDRESS" (
        "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        "STREET" VARCHAR(50),
        "NUMBER" VARCHAR(20),
        "CITY" VARCHAR(50)
        );
CREATE TABLE "PEOPLE" (
        "PERSON_ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        "FIRST_NAME" VARCHAR(50),
        "SURNAME" VARCHAR(50),
        "ADDRESS_ID" BIGINT REFERENCES ADDRESS(ID)
        );
CREATE TABLE "EMAILS" (
        "OWNER" BIGINT REFERENCES PEOPLE(PERSON_ID),
        "EMAIL" VARCHAR(80) NOT NULL PRIMARY KEY
        );
CREATE TABLE "PHONES" (
        "OWNER" BIGINT REFERENCES PEOPLE(PERSON_ID),
        "NUMBER" INTEGER NOT NULL PRIMARY KEY
        );